GET  http://localhost:8080/api/customers/pagination?page=0&limit=5

###

GET http://localhosthost:8080/api/customers/pagefiltersort?page=1&limit=10&age=21

###

GET http://localhost:8080:api/customers/filteringbyage?age=21